[package]
name = "files-to-clipboard"
version = "0.0.1"
edition = "2021"


[dependencies.windows]
version = "0.51.1"
features = [
    "Win32_System_DataExchange",
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_System_Memory"
]
